/*Generated by Claude AI
*ENSURE THIS IS EXCLUDED FROM BUILDING AS IS IT IS A TEST FILE
* WITH ITS OWN MAIN.CPP IN IT
* Contains multiple unit tests for the Leaderboard and LeaderboardManager classes
*/

#include <iostream>
#include <cassert>
#include "LeaderBoard.hpp"
#include "LeaderboardManager.hpp"

class LeaderboardUnitTest {
public:
    static void runAllTests() {
        std::cout << "=== Running Leaderboard Unit Tests ===" << std::endl;

        testManagerConnection();
        testScoreSubmission();
        testScoreFetching();
        testHighScoreDetection();
        testLeaderboardReset();
        std::cout << "\n=== All Tests Completed ===" << std::endl;
    }

private:
    static void testManagerConnection() {
        std::cout << "\n[TEST 1] Testing Firebase Connection..." << std::endl;

        LeaderboardManager manager("https://cpts122pa9-default-rtdb.firebaseio.com/leaderboard.json");

        // Try to fetch data
        LeaderboardManager::Score* scores = manager.GetLeaderBoard();

        if (scores != nullptr) {
            std::cout << "[PASS] Successfully connected to Firebase" << std::endl;
            std::cout << "Top 5 Scores:" << std::endl;
            for (int i = 0; i < 5; i++) {
                if (!scores[i].Name.empty()) {
                    std::cout << (i + 1) << ". " << scores[i].Name
                        << " - Wave " << scores[i].Waves << std::endl;
                }
                else {
                    std::cout << (i + 1) << ". ---" << std::endl;
                }
            }
        }
        else {
            std::cout << "[FAIL] Could not connect to Firebase" << std::endl;
        }
    }

    static void testScoreSubmission() {
        std::cout << "\n[TEST 2] Testing Score Submission..." << std::endl;

        LeaderboardManager manager("https://cpts122pa9-default-rtdb.firebaseio.com/leaderboard.json");

        std::string testName = "UnitTest";
        int testWaves = 999;

        bool success = manager.SendScore(testName, testWaves);

        if (success) {
            std::cout << "[PASS] Score submitted successfully" << std::endl;
        }
        else {
            std::cout << "[FAIL] Score submission failed" << std::endl;
        }
    }

    static void testScoreFetching() {
        std::cout << "\n[TEST 3] Testing Score Fetching..." << std::endl;

        Leaderboard leaderboard("https://cpts122pa9-default-rtdb.firebaseio.com/leaderboard.json");
        leaderboard.fetchScores();

        std::cout << "[INFO] Scores fetched. Check if data loads in UI test." << std::endl;
        std::cout << "[PASS] Fetch function executed without errors" << std::endl;
    }

    static void testHighScoreDetection() {
        std::cout << "\n[TEST 4] Testing High Score Detection..." << std::endl;

        Leaderboard leaderboard("https://cpts122pa9-default-rtdb.firebaseio.com/leaderboard.json");
        leaderboard.fetchScores();

        // Test various scores
        struct TestCase {
            int waves;
            bool expectedResult;
            std::string description;
        };

        std::vector<TestCase> tests = {
            {10000, true, "Very high score should qualify"},
            {1, true, "Wave 1 should qualify if board not full"},
            {0, true, "Wave 0 edge case"}
        };

        for (const auto& test : tests) {
            bool result = leaderboard.isHighScore(test.waves);
            std::cout << "  Wave " << test.waves << ": "
                << (result ? "IS" : "NOT") << " high score - "
                << test.description << std::endl;
        }

        std::cout << "[PASS] High score detection executed" << std::endl;
    }

    static void testLeaderboardReset() {
        std::cout << "\n[TEST 5] Testing Leaderboard Reset..." << std::endl;

        Leaderboard leaderboard("https://cpts122pa9-default-rtdb.firebaseio.com/leaderboard.json");

        // Fetch scores and input a name
        leaderboard.fetchScores();
        leaderboard.inputName(10);

        std::cout << "  isDone before reset: " << (leaderboard.isDone() ? "true" : "false") << std::endl;

        // Reset the leaderboard
        leaderboard.reset();

        bool isDoneAfterReset = leaderboard.isDone();
        std::cout << "  isDone after reset: " << (isDoneAfterReset ? "true" : "false") << std::endl;

        if (!isDoneAfterReset) {
            std::cout << "[PASS] Reset successfully cleared state" << std::endl;
        }
        else {
            std::cout << "[FAIL] Reset did not properly clear state" << std::endl;
        }
    }

};

int main() {
    LeaderboardUnitTest::runAllTests();

    std::cout << "\n=== Manual UI Tests ===" << std::endl;
    std::cout << "To test UI functionality, run LeaderboardTest.cpp" << std::endl;
    std::cout << "Or integrate into your main game loop for full testing." << std::endl;

    return 0;
}